### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by autoprog** [Mrivai/PELITABANGSA_ISP_EMMC_RAW_TOOL#1]
hi,

how to use it,

my case read and write emmc via isp

![image](https://user-images.githubusercontent.com/5191545/219677087-ceeaeed1-5892-4698-9217-e0f8929bdbdf.png)

enter with code ?

whats Interface use,
run with AU6438BS  usb to emmc.

in Form2 nota have (Log1) Im add.

thanks,
Carlos.

**Comment by Mrivai** [comment]
replace on Program.cs:

Auth A = new Auth();
            if (A.IsValid())
            {
                Application.Run(new Form1());
            }
            else
            {
                Application.Run(new Splash());
            }

to :

Application.Run(new Form1());

**Comment by autoprog** [comment]
hi Mrivai

thanks,
Carlos.
